import { useState, useEffect } from 'react'
import { getPayments, createPayment, deletePayment, getPaymentSummary, getStudents } from '../services/api'
import Sidebar from '../components/Sidebar'

export default function PaymentsPage() {
  const [payments, setPayments] = useState([])
  const [students, setStudents] = useState([])
  const [summary, setSummary] = useState({ totalCollected: 0, totalStudents: 0, studentsPaid: 0, studentsUnpaid: 0 })
  const [loading, setLoading] = useState(true)
  const [showForm, setShowForm] = useState(false)
  const [receipt, setReceipt] = useState(null)
  const [form, setForm] = useState({ studentId: '', amount: '', paymentDate: '', paymentMethod: 'cash', term: '', notes: '' })
  const [error, setError] = useState('')

  const fetchAll = async () => {
    try {
      const [paymentsRes, studentsRes, summaryRes] = await Promise.all([
        getPayments(), getStudents(), getPaymentSummary()
      ])
      setPayments(paymentsRes.data)
      setStudents(studentsRes.data)
      setSummary(summaryRes.data)
    } catch (err) {
      console.error(err)
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => { fetchAll() }, [])

  const handleSubmit = async (e) => {
    e.preventDefault()
    try {
      const res = await createPayment({
        studentId: parseInt(form.studentId),
        amount: parseFloat(form.amount),
        paymentDate: form.paymentDate,
        paymentMethod: form.paymentMethod,
        term: form.term,
        notes: form.notes
      })
      const student = students.find(s => s.id === parseInt(form.studentId))
      setReceipt({ ...res.data, student })
      setForm({ studentId: '', amount: '', paymentDate: '', paymentMethod: 'cash', term: '', notes: '' })
      setShowForm(false)
      setError('')
      fetchAll()
    } catch (err) {
      setError('Failed to record payment.')
    }
  }

  const handleDelete = async (id) => {
    if (!window.confirm('Delete this payment record?')) return
    await deletePayment(id)
    fetchAll()
  }

  const printReceipt = (payment) => {
    const student = students.find(s => s.id === payment.studentId)
    const receiptWindow = window.open('', '_blank', 'width=600,height=700')
    receiptWindow.document.write(`
      <html>
        <head>
          <title>Payment Receipt</title>
          <style>
            body { font-family: Arial, sans-serif; padding: 40px; color: #333; }
            .header { text-align: center; border-bottom: 2px solid #1e3a5f; padding-bottom: 20px; margin-bottom: 30px; }
            .header h1 { color: #1e3a5f; margin: 0; font-size: 24px; }
            .header p { color: #666; margin: 5px 0 0; }
            .receipt-number { text-align: right; color: #666; font-size: 13px; margin-bottom: 20px; }
            .row { display: flex; justify-content: space-between; padding: 10px 0; border-bottom: 1px solid #eee; }
            .label { color: #666; font-size: 14px; }
            .value { font-weight: bold; font-size: 14px; }
            .amount-box { background: #f0f7ff; border: 2px solid #1e3a5f; border-radius: 8px; padding: 20px; text-align: center; margin: 30px 0; }
            .amount-box p { margin: 0; color: #666; font-size: 13px; }
            .amount-box h2 { margin: 5px 0 0; color: #1e3a5f; font-size: 32px; }
            .footer { text-align: center; margin-top: 40px; color: #999; font-size: 12px; }
            .status { display: inline-block; background: #22c55e; color: white; padding: 4px 12px; border-radius: 20px; font-size: 13px; }
          </style>
        </head>
        <body>
          <div class="header">
            <h1>School Transport System</h1>
            <p>Official Payment Receipt</p>
          </div>
          <div class="receipt-number">Receipt #${payment.id.toString().padStart(5, '0')} &nbsp;&nbsp; <span class="status">PAID</span></div>
          <div class="row"><span class="label">Student Name</span><span class="value">${student?.user?.fullName || 'N/A'}</span></div>
          <div class="row"><span class="label">Grade</span><span class="value">${student?.grade || 'N/A'}</span></div>
          <div class="row"><span class="label">Payment Date</span><span class="value">${payment.paymentDate?.split('T')[0] || 'N/A'}</span></div>
          <div class="row"><span class="label">Payment Method</span><span class="value">${payment.paymentMethod?.toUpperCase()}</span></div>
          <div class="row"><span class="label">Term</span><span class="value">${payment.term || 'N/A'}</span></div>
          <div class="row"><span class="label">Notes</span><span class="value">${payment.notes || 'N/A'}</span></div>
          <div class="amount-box">
            <p>Amount Paid</p>
            <h2>KES ${Number(payment.amount).toLocaleString()}</h2>
          </div>
          <div class="footer">
            <p>This is an official receipt generated by the School Transport Management System.</p>
            <p>Generated on ${new Date().toLocaleString()}</p>
          </div>
          <script>window.print()</script>
        </body>
      </html>
    `)
    receiptWindow.document.close()
  }

  return (
    <div className="min-h-screen flex bg-gray-100">
      <Sidebar />

      <div className="flex-1 flex flex-col">
        <header className="bg-white shadow-sm px-8 py-4 flex justify-between items-center">
          <div>
            <h1 className="text-2xl font-bold text-gray-800">Payments & Fees</h1>
            <p className="text-gray-500 text-sm">Track transport fee payments and balances</p>
          </div>
          <button
            onClick={() => setShowForm(!showForm)}
            className="bg-green-500 hover:bg-green-600 text-white px-5 py-2 rounded-xl transition font-medium"
          >
            {showForm ? 'Cancel' : '+ Record Payment'}
          </button>
        </header>

        <main className="flex-1 p-8">
          {/* Receipt success banner */}
          {receipt && (
            <div className="bg-green-50 border border-green-200 rounded-2xl p-4 mb-6 flex justify-between items-center">
              <div>
                <p className="font-semibold text-green-700">Payment recorded successfully!</p>
                <p className="text-green-600 text-sm">Receipt #{receipt.id?.toString().padStart(5, '0')} generated for {receipt.student?.user?.fullName || 'student'}</p>
              </div>
              <div className="flex gap-2">
                <button
                  onClick={() => printReceipt(receipt)}
                  className="bg-green-600 hover:bg-green-700 text-white px-4 py-2 rounded-xl text-sm transition"
                >
                  Print Receipt
                </button>
                <button onClick={() => setReceipt(null)} className="text-green-600 hover:text-green-800 text-sm px-2">Dismiss</button>
              </div>
            </div>
          )}

          {/* Summary Cards */}
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 mb-8">
            <div className="bg-white rounded-2xl shadow p-5 text-center">
              <p className="text-2xl font-bold text-green-600">KES {Number(summary.totalCollected).toLocaleString()}</p>
              <p className="text-gray-500 text-sm mt-1">Total Collected</p>
            </div>
            <div className="bg-white rounded-2xl shadow p-5 text-center">
              <p className="text-2xl font-bold text-blue-600">{summary.totalStudents}</p>
              <p className="text-gray-500 text-sm mt-1">Total Students</p>
            </div>
            <div className="bg-white rounded-2xl shadow p-5 text-center">
              <p className="text-2xl font-bold text-green-600">{summary.studentsPaid}</p>
              <p className="text-gray-500 text-sm mt-1">Students Paid</p>
            </div>
            <div className="bg-white rounded-2xl shadow p-5 text-center">
              <p className="text-2xl font-bold text-red-600">{summary.studentsUnpaid}</p>
              <p className="text-gray-500 text-sm mt-1">Students Unpaid</p>
            </div>
          </div>

          {/* Payment Form */}
          {showForm && (
            <div className="bg-white rounded-2xl shadow p-6 mb-6">
              <h3 className="text-lg font-semibold mb-4">Record New Payment</h3>
              {error && <p className="text-red-500 text-sm mb-3">{error}</p>}
              <form onSubmit={handleSubmit} className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Student</label>
                  <select
                    value={form.studentId}
                    onChange={(e) => setForm({ ...form, studentId: e.target.value })}
                    className="w-full border border-gray-300 rounded-xl px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
                    required
                  >
                    <option value="">Select Student</option>
                    {students.map(s => (
                      <option key={s.id} value={s.id}>{s.user?.fullName || 'Student #' + s.id} — Grade {s.grade}</option>
                    ))}
                  </select>
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Amount (KES)</label>
                  <input
                    type="number"
                    value={form.amount}
                    onChange={(e) => setForm({ ...form, amount: e.target.value })}
                    className="w-full border border-gray-300 rounded-xl px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
                    placeholder="5000"
                    required
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Payment Date</label>
                  <input
                    type="date"
                    value={form.paymentDate}
                    onChange={(e) => setForm({ ...form, paymentDate: e.target.value })}
                    className="w-full border border-gray-300 rounded-xl px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
                    required
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Payment Method</label>
                  <select
                    value={form.paymentMethod}
                    onChange={(e) => setForm({ ...form, paymentMethod: e.target.value })}
                    className="w-full border border-gray-300 rounded-xl px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
                  >
                    <option value="cash">Cash</option>
                    <option value="mpesa">M-Pesa</option>
                    <option value="bank">Bank Transfer</option>
                    <option value="cheque">Cheque</option>
                  </select>
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Term</label>
                  <select
                    value={form.term}
                    onChange={(e) => setForm({ ...form, term: e.target.value })}
                    className="w-full border border-gray-300 rounded-xl px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
                  >
                    <option value="">Select Term</option>
                    <option value="Term 1 2026">Term 1 2026</option>
                    <option value="Term 2 2026">Term 2 2026</option>
                    <option value="Term 3 2026">Term 3 2026</option>
                  </select>
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Notes</label>
                  <input
                    type="text"
                    value={form.notes}
                    onChange={(e) => setForm({ ...form, notes: e.target.value })}
                    className="w-full border border-gray-300 rounded-xl px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
                    placeholder="Optional notes"
                  />
                </div>
                <div className="sm:col-span-2">
                  <button type="submit" className="bg-blue-600 hover:bg-blue-700 text-white px-6 py-2 rounded-xl transition">
                    Save Payment
                  </button>
                </div>
              </form>
            </div>
          )}

          {/* Payments Table */}
          <div className="bg-white rounded-2xl shadow overflow-hidden">
            <table className="w-full">
              <thead className="bg-gray-50 border-b">
                <tr>
                  <th className="text-left px-6 py-4 text-sm font-semibold text-gray-600">#</th>
                  <th className="text-left px-6 py-4 text-sm font-semibold text-gray-600">Student</th>
                  <th className="text-left px-6 py-4 text-sm font-semibold text-gray-600">Amount</th>
                  <th className="text-left px-6 py-4 text-sm font-semibold text-gray-600">Method</th>
                  <th className="text-left px-6 py-4 text-sm font-semibold text-gray-600">Term</th>
                  <th className="text-left px-6 py-4 text-sm font-semibold text-gray-600">Date</th>
                  <th className="text-left px-6 py-4 text-sm font-semibold text-gray-600">Actions</th>
                </tr>
              </thead>
              <tbody>
                {loading ? (
                  <tr><td colSpan="7" className="text-center py-20 text-gray-400">Loading...</td></tr>
                ) : payments.length === 0 ? (
                  <tr><td colSpan="7" className="text-center py-20 text-gray-400">No payments recorded yet.</td></tr>
                ) : (
                  payments.map((p, index) => (
                    <tr key={p.id} className="border-b hover:bg-gray-50 transition">
                      <td className="px-6 py-4 text-gray-400 text-sm">{index + 1}</td>
                      <td className="px-6 py-4">
                        <p className="font-medium text-gray-800">{p.student?.user?.fullName || 'N/A'}</p>
                        <p className="text-gray-400 text-xs">Grade {p.student?.grade}</p>
                      </td>
                      <td className="px-6 py-4">
                        <span className="font-bold text-green-600">KES {Number(p.amount).toLocaleString()}</span>
                      </td>
                      <td className="px-6 py-4">
                        <span className="text-xs px-3 py-1 rounded-full bg-blue-100 text-blue-700 font-medium capitalize">
                          {p.paymentMethod}
                        </span>
                      </td>
                      <td className="px-6 py-4 text-gray-500 text-sm">{p.term || 'N/A'}</td>
                      <td className="px-6 py-4 text-gray-500 text-sm">{p.paymentDate?.split('T')[0]}</td>
                      <td className="px-6 py-4 flex gap-3">
                        <button
                          onClick={() => printReceipt(p)}
                          className="text-blue-500 hover:text-blue-700 text-sm transition"
                        >
                          Receipt
                        </button>
                        <button
                          onClick={() => handleDelete(p.id)}
                          className="text-red-400 hover:text-red-600 text-sm transition"
                        >
                          Delete
                        </button>
                      </td>
                    </tr>
                  ))
                )}
              </tbody>
            </table>
          </div>
        </main>
      </div>
    </div>
  )
}